// Command guides writes guides/guides.json: a short, Wikivoyage-grounded intro for each of the
// starter cities, generated by a local Ollama model. It is a standalone, offline tool: its
// output is unreviewed, and the site shows an entry only after a person has reviewed it and set
// "reviewed" in the file. A regenerated entry is therefore hidden until reviewed again. See
// README.md (City guides), tasks/guides-review.md and docs/maintenance.md for the workflow.
package main

import (
	"context"
	"flag"
	"log"
	"os"
	"os/signal"
	"strings"
	"time"

	"weatherservice/internal/guides"
)

func main() {
	log.SetFlags(0)

	out := flag.String("out", "guides/guides.json", "the guides.json file to read and write")
	ollamaURL := flag.String("ollama", "http://localhost:11434", "the local Ollama server's base URL")
	model := flag.String("model", "mistral:7b", "the Ollama model to ask for intros")
	only := flag.String("only", "", "comma-separated city names to run, instead of all 20 (e.g. -only=Lisbon)")
	timeout := flag.Duration("timeout", 30*time.Minute, "how long the whole run may take")
	flag.Parse()

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	ctx, cancel := context.WithTimeout(ctx, *timeout)
	defer cancel()

	cities := selectCities(*only)

	existing, err := guides.LoadGuides(*out)
	if err != nil {
		log.Fatalf("guides: loading %s: %v", *out, err)
	}

	fetcher := guides.NewWikivoyageAPI(nil)
	generator := guides.NewOllamaClient(nil, *ollamaURL, *model)

	result, skipped := guides.Run(ctx, cities, existing, fetcher, generator, time.Now)

	if err := guides.WriteGuides(*out, result); err != nil {
		log.Fatalf("guides: writing %s: %v", *out, err)
	}

	log.Printf("guides: wrote %s (%d cities, %d skipped)", *out, len(result), len(skipped))

	for _, s := range skipped {
		log.Printf("guides: skipped %s: %s", s.Slug, s.Reason)
	}
}

// selectCities returns guides.Cities, or just the named ones when -only was given.
func selectCities(only string) []guides.City {
	if only == "" {
		return guides.Cities
	}

	wanted := map[string]bool{}
	for _, name := range strings.Split(only, ",") {
		wanted[strings.TrimSpace(name)] = true
	}

	var selected []guides.City

	for _, c := range guides.Cities {
		if wanted[c.Name] {
			selected = append(selected, c)
		}
	}

	return selected
}
