// Requires the milestone fixture on :8087 and a separate Chromium CDP instance on :9227.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const output = new URL('.', import.meta.url);
const tabs = await (await fetch('http://127.0.0.1:9227/json/list')).json();
const ws = new WebSocket(tabs[0].webSocketDebuggerUrl);
await new Promise(r => ws.addEventListener('open', r, {once:true}));
let id=0;const pending=new Map(),errors=[],responses=[];
ws.addEventListener('message', e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown') errors.push(m.params.exceptionDetails);else if(m.method==='Network.responseReceived'&&/127.0.0.1:8087/.test(m.params.response.url))responses.push({url:m.params.response.url,status:m.params.response.status});});
const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
const js=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const until=async expression=>{for(let n=0;n<150;n++){if(await js(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+expression);};
const shot=async name=>{const {data}=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(new URL(name+'.png',output),Buffer.from(data,'base64'));};
await call('Page.enable');await call('Runtime.enable');await call('Network.enable');await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
const layouts=[];
for(const [width,height] of [[375,812],[768,1024],[1100,1000],[1440,1000]]) {
 await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<640});
 await call('Page.navigate',{url:'http://127.0.0.1:8087/'});
 await until(`document.readyState==='complete'&&!!document.querySelector('.destination-banner')&&typeof htmx!=='undefined'`);
 const layout=await js(`({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,heroHeight:document.querySelector('.destination-banner').getBoundingClientRect().height,photoLoaded:document.querySelector('.destination-image')?.naturalWidth>0,mapTop:document.querySelector('.tt-overview-map').getBoundingClientRect().top,formTop:document.querySelector('.tt-overview-planner').getBoundingClientRect().top,ids:['overview','itinerary','stays','videos'].map(id=>document.querySelectorAll('#'+id).length)})`);
 assert.ok(layout.scrollWidth<=width);assert.deepEqual(layout.ids,[1,1,1,1]);assert.equal(layout.photoLoaded,true);
 if(width<900) assert.ok(layout.formTop<layout.mapTop);
 layouts.push(layout);await shot('initial-'+width);
}
await call('Emulation.setDeviceMetricsOverride',{width:375,height:812,deviceScaleFactor:1,mobile:true});
await js(`document.querySelector('.tt-menu-button').click()`);assert.equal(await js(`document.querySelector('.tt-menu-button').getAttribute('aria-expanded')`),'true');
await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
assert.equal(await js(`document.querySelector('.tt-menu-button').getAttribute('aria-expanded')`),'false');
await js(`document.querySelector('.tt-skip-link').click()`);assert.equal(await js(`document.activeElement.id`),'overview');
await js(`document.querySelector('.trip-form').requestSubmit()`);await until(`document.querySelectorAll('#itinerary .trip-day').length===3`);
assert.equal(await js(`document.querySelectorAll('#trip-card .trip-day').length`),0);assert.equal(await js(`document.querySelectorAll('#stays .stay').length`),2);
await js(`document.querySelector('[data-tt-section="itinerary"]').click()`);await until(`document.activeElement.id==='itinerary'`);
await shot('planned-375');
await js(`document.querySelector('[name=days]').value='4';document.querySelector('.trip-form').requestSubmit()`);await until(`!!document.querySelector('.trip-error')`);
assert.equal(await js(`document.querySelectorAll('.trip-day,.stay').length`),0);
await js(`document.querySelector('[name=days]').value='3';document.querySelector('.trip-form').requestSubmit()`);await until(`document.querySelectorAll('.trip-day').length===3`);
await js(`document.querySelector('[name=lat]').value='NaN';document.querySelector('.trip-form').requestSubmit()`);await until(`!!document.querySelector('.trip-error')`);assert.equal(await js(`document.querySelectorAll('.trip-day,.stay').length`),0);
await js(`document.querySelector('[name=city_name]').value='error';document.querySelector('#destination-search').requestSubmit()`);await until(`!!document.querySelector('#destination-search-error').textContent.trim()`);assert.equal(await js(`document.querySelector('.destination-title').textContent`),'Lisbon');
await js(`document.querySelector('[name=city_name]').value='A very long unconfigured destination name';document.querySelector('#destination-search').requestSubmit()`);await until(`document.querySelector('.destination-title').textContent==='A very long unconfigured destination name'`);
assert.equal(await js(`document.querySelectorAll('.destination-image').length`),0);assert.equal(await js(`document.documentElement.scrollWidth`),375);await js(`window.scrollTo(0,0)`);await shot('fallback-375');
await js(`document.querySelector('[name=city_name]').value='Lisbon';document.querySelector('#destination-search').requestSubmit()`);await until(`!!document.querySelector('.destination-image')`);
await js(`document.querySelector('.destination-image').src='/missing-fixture-photo.jpg'`);await until(`document.querySelector('.destination-image').hidden`);assert.equal(await js(`document.documentElement.scrollWidth`),375);await shot('failed-photo-375');
await js(`window.scrollTo(0,document.documentElement.scrollHeight)`);
await until(`document.querySelector('.tt-bottom-navigation [data-tt-section="videos"]').getAttribute('aria-current')==='location'`);
const clearance=await js(`({footerBottom:document.querySelector('footer').getBoundingClientRect().bottom,barTop:document.querySelector('.tt-bottom-navigation').getBoundingClientRect().top})`);
assert.ok(clearance.footerBottom<=clearance.barTop, 'bottom navigation must not cover footer');
assert.deepEqual(errors,[]);
await fs.writeFile(new URL('results.json',output),JSON.stringify({layouts,checks:['menu Escape','skip focus','section focus','real HTMX plan OOB','400/500 clear stale results','search error preserves city','unknown-city fallback','long mobile city','failed hero fallback','bottom navigation clearance and shared active state'],map:'Explicit local fixture map; live provider not checked',errors,responses},null,2));
console.log(JSON.stringify({layouts,errors,checks:'passed'},null,2));ws.close();
